# Sets window's CSC specific flags.

SET(WIN32 1)

SET(CMAKE_CREATE_WIN32_EXE /target:winexe)
SET(CMAKE_CREATE_CONSOLE_EXE /target:exe)

IF(CMAKE_VERBOSE_MAKEFILE)
    SET(CMAKE_CSC_NOLOGO "")
ELSE()
    SET(CMAKE_CSC_NOLOGO "/nologo")
ENDIF()

IF(CMAKE_GENERATOR MATCHES "Visual Studio")
    SET(CMAKE_NO_BUILD_TYPE 1)
    SET(CMAKE_CONFIGURATION_TYPES
        "Debug;Release;MinSizeRel;RelWithDebInfo"
        CACHE STRING
        "Semicolon separated list of supported configuration types, only supports Debug, Release, MinSizeRel, and RelWithDebInfo, anything else will be ignored."
        )
    MARK_AS_ADVANCED(CMAKE_CONFIGURATION_TYPES)
ENDIF()

SET(CMAKE_CSC_FLAGS_INIT "")
SET(CMAKE_CSC_FLAGS_DEBUG_INIT "")
SET(CMAKE_CSC_FLAGSRELWITHDEBINFO "")
SET(CMAKE_CSC_FLAGS_RELEASE_INIT "")
SET(CMAKE_CSC_FLAGS_MINSIZEREL_INIT "")


SET(CMAKE_EXE_LINKER_FLAGS_INIT "/DWIN32 ${CMAKE_CSC_NOLOGO}")
SET(CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT "/DDEBUG /debug /pdb:full")
SET(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO_INIT "/debug /pdb:full")
SET(CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT "/optimize")
SET(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL_INIT "")
